### ISSUE TITLE
Prepare release v4.0.0-beta

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#58]
Currently installation is tedious (especially for newbies), so I guess we should pack up simple release tarball/zip, even though not everything is complete.
# Open bug issues at the time of creating this list
- [ ] [Runtime script reload messes up y_commands](https://github.com/Misiur/YSI-Includes/issues/6) 
- [ ] [Fix hooking timers](https://github.com/Misiur/YSI-Includes/issues/27)
- [ ] [Include order doing funky stuff](https://github.com/Misiur/YSI-Includes/issues/37)
- [x] [Make sure y_hooks expansions aren't funky](https://github.com/Misiur/YSI-Includes/issues/43)
- [ ] [Check out y_properties usage/deps](https://github.com/Misiur/YSI-Includes/issues/47)
- [ ] [Do something about y_text](https://github.com/Misiur/YSI-Includes/issues/48)
- [ ] [Really do something about y_text (and things depending on it)](https://github.com/Misiur/YSI-Includes/issues/49)
- [ ] [y_text buffer sizes are wonky (?)](https://github.com/Misiur/YSI-Includes/issues/55)
- [ ] [Investigate y_master errors](https://github.com/Misiur/YSI-Includes/issues/50)
- [ ] [Fix Reverse iterator to use new macro expansions](https://github.com/Misiur/YSI-Includes/issues/57)
# Requested features
- [ ] [Add foreach counting extension](https://github.com/Misiur/YSI-Includes/issues/54)
- [ ] [y_dialogs/normal dialogs compat mode?](https://github.com/Misiur/YSI-Includes/issues/45)
- [ ] [Allow timers to be used with area checking](https://github.com/Misiur/YSI-Includes/issues/32)
- [ ] [Fetch message from y_text into a string](https://github.com/Misiur/YSI-Includes/issues/20)
- [ ] [Punycode enhancements](https://github.com/Misiur/YSI-Includes/issues/29)
- [ ] [Implement more backends for svar (useful for a lot of other YSI libs as well)](https://github.com/Misiur/YSI-Includes/issues/46)
- [ ] [Make QWERTYUIOP 4.0 compatible](https://github.com/Misiur/YSI-Includes/issues/30)
# Misc
- [ ] [Good stuff about states, move to wiki](https://github.com/Misiur/YSI-Includes/issues/33)
